### ISSUE TITLE
thursday session

### ISSUE THREAD

**Issue by skasim** [samxj/gutenberg_scifi#19]
Hi Nathan,

I was pretty sick the last couple of weeks, so I wasn't able to do any coding. I am starting today on the Pandas tutorial you sent before and will try to work through it and other resources you sent last week before our session Thursday.

If it is alright with you, I'd like to keep our session this Thursday because I think it would be useful to start working on Pandas and also because I am working on this Top Performer course (http://www.scotthyoung.com/courses/top-performer-course/) and part of my hw for the course is to speak with professionals who are ahead of me in the type of career I want and see what I glean from it. I wanted to see if we could 20-30 minutes from our session this week and discuss career related questions.

Thanks!!
Samra

**Comment by ndanielsen** [comment]
Hi Samra, sure works for me. We can do as much pandas as you'd like. For career related questions, I'm very open to it.
